version: "4.0"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongodb
    networks: 
      - mongo-net

  mongodb:
    image: mongo:latest 
    container_name: my-mongodb 
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:latest 
    container_name: my-mongo-express 
    restart: always 
    depends_on:
      - mongodb 
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb 
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: root 
      ME_CONFIG_MONGODB_AUTH_PASSWORD: examplepassword 
      ME_CONFIG_BASICAUTH_USERNAME: admin 
      ME_CONFIG_BASICAUTH_PASSWORD: password 
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge 

volumes:
  mongo-data:
    driver: local 
